/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PricingPlan = IDL.Record({
  'localPrice' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'usdEquivalent' : IDL.Text,
  'period' : IDL.Text,
  'name' : IDL.Text,
});
export const CountryPricing = IDL.Record({
  'country' : IDL.Text,
  'plans' : IDL.Vec(PricingPlan),
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'durationWeeks' : IDL.Nat,
});
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCourse' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'getAllCategories' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'icon' : IDL.Text,
            'name' : IDL.Text,
            'description' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getAllCountryPricing' : IDL.Func([], [IDL.Vec(CountryPricing)], ['query']),
  'getAvailableCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getCountryPricing' : IDL.Func([IDL.Text], [CountryPricing], ['query']),
  'getCourse' : IDL.Func([IDL.Nat], [Course], ['query']),
  'getCoursesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Course)], ['query']),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PricingPlan = IDL.Record({
    'localPrice' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'usdEquivalent' : IDL.Text,
    'period' : IDL.Text,
    'name' : IDL.Text,
  });
  const CountryPricing = IDL.Record({
    'country' : IDL.Text,
    'plans' : IDL.Vec(PricingPlan),
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'durationWeeks' : IDL.Nat,
  });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'addCourse' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'getAllCategories' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'icon' : IDL.Text,
              'name' : IDL.Text,
              'description' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getAllCountryPricing' : IDL.Func([], [IDL.Vec(CountryPricing)], ['query']),
    'getAvailableCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getCountryPricing' : IDL.Func([IDL.Text], [CountryPricing], ['query']),
    'getCourse' : IDL.Func([IDL.Nat], [Course], ['query']),
    'getCoursesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Course)], ['query']),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };