/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface CountryPricing {
  'country' : string,
  'plans' : Array<PricingPlan>,
}
export interface Course {
  'id' : bigint,
  'title' : string,
  'isAvailable' : boolean,
  'description' : string,
  'category' : string,
  'durationWeeks' : bigint,
}
export interface PricingPlan {
  'localPrice' : string,
  'features' : Array<string>,
  'usdEquivalent' : string,
  'period' : string,
  'name' : string,
}
export interface _SERVICE {
  'addCourse' : ActorMethod<
    [string, string, bigint, string, boolean],
    undefined
  >,
  'getAllCategories' : ActorMethod<
    [],
    Array<{ 'icon' : string, 'name' : string, 'description' : string }>
  >,
  'getAllCountryPricing' : ActorMethod<[], Array<CountryPricing>>,
  'getAvailableCourses' : ActorMethod<[], Array<Course>>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getCountryPricing' : ActorMethod<[string], CountryPricing>,
  'getCourse' : ActorMethod<[bigint], Course>,
  'getCoursesByCategory' : ActorMethod<[string], Array<Course>>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];